# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
#plugin 'cocoapods-fix-react-native'
target 'LeanNodeProject' do
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'React', path: rn_path, subspecs: [
    'Core',
        'CxxBridge',
        'DevSupport',
        'RCTActionSheet',
        'RCTGeolocation',
        'RCTText',
        'RCTNetwork',
        'RCTWebSocket',
        'RCTNetwork',
        'RCTVibration',
        'RCTSettings',
        'RCTAnimation',
        'RCTLinkingIOS',
        'RCTImage',
  ]

    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
    pod 'react-native-maps', path: rn_maps_path
    pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
    pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end

end